// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using squittal.ScrimPlanetmans.App.Data;

#nullable disable

namespace squittal.ScrimPlanetmans.App.Migrations
{
    [DbContext(typeof(PlanetmansDbContext))]
    [Migration("20230326100629_FixMoreViews")]
    partial class FixMoreViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ConstructedTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHiddenFromSelection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ConstructedTeam", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ConstructedTeamPlayerMembership", b =>
                {
                    b.Property<int>("ConstructedTeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("CharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.HasKey("ConstructedTeamId", "CharacterId");

                    b.ToTable("ConstructedTeamPlayerMembership", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimDamageAssist", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AttackerCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("VictimCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<long?>("AttackerLoadoutId")
                        .HasColumnType("bigint");

                    b.Property<int?>("AttackerTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceGainAmount")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceGainId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScrimMatchRound")
                        .HasColumnType("int");

                    b.Property<int?>("VictimTeamOrdinal")
                        .HasColumnType("int");

                    b.HasKey("ScrimMatchId", "Timestamp", "AttackerCharacterId", "VictimCharacterId");

                    b.ToTable("ScrimDamageAssist", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimDeath", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AttackerCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("VictimCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int?>("AttackerFactionId")
                        .HasColumnType("int");

                    b.Property<long>("AttackerLoadoutId")
                        .HasColumnType("bigint");

                    b.Property<int?>("AttackerTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int?>("AttackerVehicleId")
                        .HasColumnType("int");

                    b.Property<int>("DeathType")
                        .HasColumnType("int");

                    b.Property<bool>("IsHeadshot")
                        .HasColumnType("bit");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("ScrimMatchRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-1);

                    b.Property<int>("VictimFactionId")
                        .HasColumnType("int");

                    b.Property<long>("VictimLoadoutId")
                        .HasColumnType("bigint");

                    b.Property<int?>("VictimTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<long?>("WeaponId")
                        .HasColumnType("bigint");

                    b.HasKey("ScrimMatchId", "Timestamp", "AttackerCharacterId", "VictimCharacterId");

                    b.ToTable("ScrimDeath", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimFacilityControl", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("ControllingTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int>("ControlType")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScrimMatchRound")
                        .HasColumnType("int");

                    b.HasKey("ScrimMatchId", "Timestamp", "FacilityId", "ControllingTeamOrdinal");

                    b.ToTable("ScrimFacilityControl", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimGrenadeAssist", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AttackerCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("VictimCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int?>("AttackerTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceGainId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScrimMatchRound")
                        .HasColumnType("int");

                    b.Property<int?>("VictimTeamOrdinal")
                        .HasColumnType("int");

                    b.HasKey("ScrimMatchId", "Timestamp", "AttackerCharacterId", "VictimCharacterId");

                    b.ToTable("ScrimGrenadeAssist", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RulesetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-1);

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RulesetId")
                        .IsUnique();

                    b.ToTable("ScrimMatch", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatchParticipatingPlayer", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("ConstructedTeamId")
                        .HasColumnType("int");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFromConstructedTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsFromOutfit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NameDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OutfitId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("PrestigeLevel")
                        .HasColumnType("int");

                    b.Property<int>("TeamOrdinal")
                        .HasColumnType("int");

                    b.HasKey("ScrimMatchId", "CharacterId");

                    b.ToTable("ScrimMatchParticipatingPlayer", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatchRoundConfiguration", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ScrimMatchRound")
                        .HasColumnType("int");

                    b.Property<long?>("FacilityId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsManualWorldId")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRoundEndedOnFacilityCapture")
                        .HasColumnType("bit");

                    b.Property<int>("RoundSecondsTotal")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorldId")
                        .HasColumnType("int");

                    b.HasKey("ScrimMatchId", "ScrimMatchRound");

                    b.ToTable("ScrimMatchRoundConfiguration", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatchTeamPointAdjustment", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TeamOrdinal")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScrimMatchId", "TeamOrdinal", "Timestamp");

                    b.ToTable("ScrimMatchTeamPointAdjustment", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatchTeamResult", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("BaseCaptures")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("BaseDefenses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedDeaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Deaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HeadshotDeaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Headshots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Kills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NetScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ObjectiveCaptureTicks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ObjectiveDefenseTicks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RevivesGiven")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RevivesTaken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Suicides")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamkillDeaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Teamkills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UtilityAssistedDeaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UtilityAssists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ScrimMatchId", "TeamOrdinal");

                    b.ToTable("ScrimMatchTeamResult", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimRevive", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MedicCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("RevivedCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceGainAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ExperienceGainId")
                        .HasColumnType("int");

                    b.Property<long?>("MedicLoadoutId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MedicTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long?>("RevivedLoadoutId")
                        .HasColumnType("bigint");

                    b.Property<int?>("RevivedTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("ScrimMatchRound")
                        .HasColumnType("int");

                    b.Property<int>("WorldId")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("ScrimMatchId", "Timestamp", "MedicCharacterId", "RevivedCharacterId");

                    b.ToTable("ScrimRevive", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimSpotAssist", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SpotterCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("VictimCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScrimMatchRound")
                        .HasColumnType("int");

                    b.Property<int?>("SpotterTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int?>("VictimTeamOrdinal")
                        .HasColumnType("int");

                    b.HasKey("ScrimMatchId", "Timestamp", "SpotterCharacterId", "VictimCharacterId");

                    b.ToTable("ScrimSpotAssist", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimVehicleDestruction", b =>
                {
                    b.Property<string>("ScrimMatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AttackerCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("VictimCharacterId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("VictimVehicleId")
                        .HasColumnType("bigint");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<long?>("AttackerVehicleId")
                        .HasColumnType("bigint");

                    b.Property<int>("DeathType")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScrimMatchRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-1);

                    b.Property<long?>("WeaponId")
                        .HasColumnType("bigint");

                    b.HasKey("ScrimMatchId", "Timestamp", "AttackerCharacterId", "VictimCharacterId", "VictimVehicleId");

                    b.ToTable("ScrimVehicleDestruction", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Models.ScrimMatchReports.ScrimMatchReportInfantryDeath", b =>
                {
                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("AttackerCharacterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AttackerFactionId")
                        .HasColumnType("int");

                    b.Property<int>("AttackerLoadoutId")
                        .HasColumnType("int");

                    b.Property<string>("AttackerNameDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AttackerTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("ConcussionGrenadeAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathType")
                        .HasColumnType("int");

                    b.Property<int>("EmpGrenadeAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FlashGrenadeAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GrenadeAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("IsHeadshot")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsTrickleDeath")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ScrimMatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScrimMatchRound")
                        .HasColumnType("int");

                    b.Property<int?>("SecondsFromPreviousDeathEvent")
                        .HasColumnType("int");

                    b.Property<int?>("SecondsToNextDeathEvent")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("VictimCharacterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VictimFactionId")
                        .HasColumnType("int");

                    b.Property<int>("VictimLoadoutId")
                        .HasColumnType("int");

                    b.Property<string>("VictimNameDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VictimTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.Property<string>("WeaponName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("View_ScrimMatchReportInfantryDeaths", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Models.ScrimMatchReports.ScrimMatchReportInfantryPlayerClassEventCounts", b =>
                {
                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamageAssistsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EventsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EventsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EventsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EventsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EventsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EventsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("KillsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NameDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrestigeLevel")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ScrimMatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamOrdinal")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("View_ScrimMatchReportInfantryPlayerClassEventCounts", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Models.ScrimMatchReports.ScrimMatchReportInfantryPlayerHeadToHeadStats", b =>
                {
                    b.Property<int>("AssistedDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("AssistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedOnlyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedOnlyKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsTaken")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Deaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GrenadeAssistedDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GrenadeAssistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GrenadeAssistedOnlyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GrenadeAssistedOnlyKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HeadshotDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HeadshotKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NetScore")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("OpponentCharacterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpponentFactionId")
                        .HasColumnType("int");

                    b.Property<string>("OpponentNameDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpponentNameFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpponentPrestigeLevel")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("OpponentTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<string>("PlayerCharacterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerFactionId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerNameDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerPrestigeLevel")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PlayerTeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoredDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ScrimMatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpotAssistedDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SpotAssistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SpotAssistedOnlyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SpotAssistedOnlyKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UnassistedDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UnassistedHeadshotDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UnassistedHeadshotKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UnassistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ZeroPointDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.ToTable((string)null);

                    b.ToView("View_ScrimMatchReportInfantryPlayerHeadToHeadStats", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Models.ScrimMatchReports.ScrimMatchReportInfantryPlayerRoundStats", b =>
                {
                    b.Property<int>("AssistDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("AssistedKills")
                        .HasColumnType("int");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamageAssistedDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageTeamAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Deaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("HeadshotEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HeadshotKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NameDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NetScore")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PrestigeLevel")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoredDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ScrimMatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScrimMatchRound")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("Suicides")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamKillDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TrickleDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UnassistedEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ZeroPointDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.ToTable((string)null);

                    b.ToView("View_ScrimMatchReportInfantryPlayerRoundStats", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Models.ScrimMatchReports.ScrimMatchReportInfantryPlayerStats", b =>
                {
                    b.Property<int>("AssistDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("AssistedKills")
                        .HasColumnType("int");

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamageAssistedDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageTeamAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Deaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("HeadshotEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HeadshotKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NameDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NetScore")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PrestigeLevel")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoredDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ScrimMatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpotAssistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("Suicides")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamKillDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("TotalDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TrickleDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UnassistedEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ZeroPointDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.ToTable((string)null);

                    b.ToView("View_ScrimMatchReportInfantryPlayerStats", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Models.ScrimMatchReports.ScrimMatchReportInfantryPlayerWeaponStats", b =>
                {
                    b.Property<int>("AssistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("AssistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("AssistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("CharacterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamageAssistedDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Deaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("HeadshotDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HeadshotEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HeadshotKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HeadshotTeamkills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NameDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PrestigeLevel")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoredDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoredKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ScrimMatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Suicides")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("TeamkillDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Teamkills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UnassistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("UnassistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("UnassistedHeadshotDeaths")
                        .HasColumnType("int");

                    b.Property<int>("UnassistedHeadshotEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("UnassistedHeadshotKills")
                        .HasColumnType("int");

                    b.Property<int>("UnassistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.Property<int>("ZeroPointDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ZeroPointKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.ToTable((string)null);

                    b.ToView("View_ScrimMatchReportInfantryPlayerWeaponStats", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Models.ScrimMatchReports.ScrimMatchReportInfantryTeamRoundStats", b =>
                {
                    b.Property<int>("AssistDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("AssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssistedDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageTeamAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Deaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FacilityCapturePoints")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GrenadeAssistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssists")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeTeamAssists")
                        .HasColumnType("int");

                    b.Property<int>("HeadshotEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HeadshotKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NetScore")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoredDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ScrimMatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScrimMatchRound")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssists")
                        .HasColumnType("int");

                    b.Property<int>("Suicides")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamKillDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("TotalDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TrickleDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UnassistedEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ZeroPointDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.ToTable((string)null);

                    b.ToView("View_ScrimMatchReportInfantryTeamRoundStats", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Models.ScrimMatchReports.ScrimMatchReportInfantryTeamStats", b =>
                {
                    b.Property<int>("AssistDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("AssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssistedDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("DamageAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageAssistsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DamageTeamAssists")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Deaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DeathsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FacilityCapturePoints")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GrenadeAssistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeAssists")
                        .HasColumnType("int");

                    b.Property<int>("GrenadeTeamAssists")
                        .HasColumnType("int");

                    b.Property<int>("HeadshotEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("HeadshotKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsEngineer")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsHeavyAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsInfiltrator")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsLightAssault")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsMax")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("KillsAsMedic")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("NetScore")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PointAdjustments")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScoredDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ScrimMatchId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpotAssistedDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedKills")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyEnemyDeaths")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssistedOnlyKills")
                        .HasColumnType("int");

                    b.Property<int>("SpotAssists")
                        .HasColumnType("int");

                    b.Property<int>("Suicides")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamKillDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamKills")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TeamOrdinal")
                        .HasColumnType("int");

                    b.Property<int>("TotalDamageDealt")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TrickleDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UnassistedEnemyDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ZeroPointDeaths")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.ToTable((string)null);

                    b.ToView("View_ScrimMatchReportInfantryTeamStats", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.Ruleset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DefaultEndRoundOnFacilityCapture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DefaultMatchTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultRoundLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(900);

                    b.Property<bool>("IsCustomDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceFile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.ToTable("Ruleset", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetActionRule", b =>
                {
                    b.Property<int>("RulesetId")
                        .HasColumnType("int");

                    b.Property<int>("ScrimActionType")
                        .HasColumnType("int");

                    b.Property<bool>("DeferToItemCategoryRules")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScrimActionTypeDomain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(-1);

                    b.HasKey("RulesetId", "ScrimActionType");

                    b.ToTable("RulesetActionRule", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetFacilityRule", b =>
                {
                    b.Property<int>("RulesetId")
                        .HasColumnType("int");

                    b.Property<long>("FacilityId")
                        .HasColumnType("bigint");

                    b.HasKey("RulesetId", "FacilityId");

                    b.ToTable("RulesetFacilityRule", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetItemCategoryRule", b =>
                {
                    b.Property<int>("RulesetId")
                        .HasColumnType("int");

                    b.Property<long>("ItemCategoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("DeferToItemRules")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("DeferToPlanetsideClassSettings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EngineerIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EngineerPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("HeavyAssaultIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("HeavyAssaultPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("InfiltratorIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("InfiltratorPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("LightAssaultIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LightAssaultPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("MaxIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("MedicIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MedicPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("RulesetId", "ItemCategoryId");

                    b.ToTable("RulesetItemCategoryRule", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetItemRule", b =>
                {
                    b.Property<int>("RulesetId")
                        .HasColumnType("int");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("DeferToPlanetsideClassSettings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EngineerIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("EngineerPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("HeavyAssaultIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("HeavyAssaultPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("InfiltratorIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("InfiltratorPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("ItemCategoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("LightAssaultIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LightAssaultPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("MaxIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("MedicIsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MedicPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("RulesetId", "ItemId");

                    b.ToTable("RulesetItemRule", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetOverlayConfiguration", b =>
                {
                    b.Property<int>("RulesetId")
                        .HasColumnType("int");

                    b.Property<bool?>("ShowStatusPanelScores")
                        .HasColumnType("bit");

                    b.Property<int>("StatsDisplayType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("UseCompactLayout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("RulesetId");

                    b.ToTable("RulesetOverlayConfiguration", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.ScrimAction", b =>
                {
                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Domain")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Action");

                    b.ToTable("ScrimAction", (string)null);
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ConstructedTeamPlayerMembership", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.App.Data.Models.ConstructedTeam", "ConstructedTeam")
                        .WithMany("PlayerMemberships")
                        .HasForeignKey("ConstructedTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConstructedTeam");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatch", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.Ruleset", "Ruleset")
                        .WithOne()
                        .HasForeignKey("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatch", "RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatchRoundConfiguration", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatch", "ScrimMatch")
                        .WithMany()
                        .HasForeignKey("ScrimMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrimMatch");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatchTeamPointAdjustment", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatchTeamResult", "ScrimMatchTeamResult")
                        .WithMany("PointAdjustments")
                        .HasForeignKey("ScrimMatchId", "TeamOrdinal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrimMatchTeamResult");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetActionRule", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.Ruleset", "Ruleset")
                        .WithMany("RulesetActionRules")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetFacilityRule", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.Ruleset", "Ruleset")
                        .WithMany("RulesetFacilityRules")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetItemCategoryRule", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.Ruleset", "Ruleset")
                        .WithMany("RulesetItemCategoryRules")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetItemRule", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.Ruleset", "Ruleset")
                        .WithMany("RulesetItemRules")
                        .HasForeignKey("RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetOverlayConfiguration", b =>
                {
                    b.HasOne("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.Ruleset", "Ruleset")
                        .WithOne("RulesetOverlayConfiguration")
                        .HasForeignKey("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.RulesetOverlayConfiguration", "RulesetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruleset");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ConstructedTeam", b =>
                {
                    b.Navigation("PlayerMemberships");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.Data.Models.ScrimMatchTeamResult", b =>
                {
                    b.Navigation("PointAdjustments");
                });

            modelBuilder.Entity("squittal.ScrimPlanetmans.App.ScrimMatch.Ruleset.Models.Ruleset", b =>
                {
                    b.Navigation("RulesetActionRules");

                    b.Navigation("RulesetFacilityRules");

                    b.Navigation("RulesetItemCategoryRules");

                    b.Navigation("RulesetItemRules");

                    b.Navigation("RulesetOverlayConfiguration");
                });
#pragma warning restore 612, 618
        }
    }
}
